
services:
  game:
    build:
      context: ./GameServerService
      dockerfile: Dockerfile
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - test-net

networks:
  test-net:
    driver: bridge
